### ISSUE TITLE
Sometimes project popup card stays

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet-org/planet-webapp#117]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/27153515/91651231-c2fcb200-eaa7-11ea-9f66-976ecaade8af.gif)

**Comment by harshvitra** [comment]
I tried to solve this 

The timer is set multiple times for one hover
while moving out it is set to undefined, 

The problem is that if it set 2 times and on hovering out only undefined once it will stay

![asdsadad](https://user-images.githubusercontent.com/25605193/92188746-075aca00-ee7b-11ea-9f3c-f1d5cdad6c77.PNG)
