### ISSUE TITLE
Project Description - Font Size of Site-Owner Attribute

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-webapp#577]
The Font Size of "Private" (which is the Site Owner Status) is a bit too big.

(It is bigger than the header right above)

Used this address: https://v2.trilliontreecampaign.org/yucatan-reforestation
In this browser: Firefox, Version 83.0 (64-Bit)

![project_private_font_size](https://user-images.githubusercontent.com/18365824/101188835-861bfa80-3656-11eb-9c98-11631ffb7c2c.PNG)

**Comment by harshvitra** [comment]
Not sure if its a bug as this was part of the design. So it might be intentional, if not we'll make the changes. 

@felixfinkbeiner your comments? 

<img width="299" alt="Screenshot 2020-12-05 at 11 20 19 PM" src="https://user-images.githubusercontent.com/25605193/101259704-74b71900-3750-11eb-86e0-b6416c756d16.png">

**Comment by felixfinkbeiner** [comment]
Please improve it :)

**Comment by sagararyal** [comment]
@harshvitra try with reduced font size, same as general text but bold.

**Comment by harshvitra** [comment]
This is fixed
